### ISSUE TITLE
What stack shall we use? 

### ISSUE THREAD

**Issue by lucyrose93** [lucyrose93/MakaTalk#25]
@smarthutza we should look into what technologies we want to use to build this, front end and back end.

**Comment by lucyrose93** [comment]
**OUR STACK** 🥞 

- PSQL
- HAPI 
- NODE
- JS
- HTML5
- CSS3

***
- TRAVIS
- CODECOV
- TAPE

@smarthutza @des-des

**Comment by des-des** [comment]
+ Handlebars
